HwidProtectionServer/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using HwidProtectionServer.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using HwidProtectionServer.Models;
using HwidProtectionServer.ViewModels;

namespace HwidProtectionServer.Controllers
{
    public class AuthController : Controller
    {
        // GET: Auth
        public ActionResult Index()
        {
            return RedirectToAction("Login");
        }

        // GET: Login
        public ActionResult Login()
        {
            var user = HttpContext.Session.GetObject<User>("user");
            if (user != null)
            {
                return RedirectToAction("Index", "Home");
            }
            return View(new BaseViewModel { User = null });
        }

        // POST: Login
        [HttpPost]
        public ActionResult Login(User user)
        {
            User userFound =
                UsersRepository.Users.FirstOrDefault(u => u.Username == user.Username && u.Password == user.Password);

            if (userFound != null)
            {
                HttpContext.Session.SetObject("user", userFound);
                RedirectToAction("Index", "Home");
            }

            return RedirectToAction("Login");
        }

        // GET: Logout
        public ActionResult Logout()
        {
            HttpContext.Session.Remove("user");
            return RedirectToAction("Index", "Home");
        }
    }
}

HwidProtectionServer/Controllers/HwidController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HwidProtectionServer.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HwidProtectionServer.Models;
using HwidProtectionServer.ViewModels;
using Microsoft.AspNetCore.Http;

namespace HwidProtectionServer.Controllers
{
    public class HwidController : Controller
    {
        private readonly HwidProtectionServerContext _context;

        public HwidController(HwidProtectionServerContext context)
        {
            _context = context;
        }

        // GET: Hwid
        public IActionResult Index()
        {
            User user = HttpContext.Session.GetObject<User>("user");
            if (user == null)
            {
                return RedirectToAction("Index", "Auth");
            }

            return View(new HwidsViewModel
            {
                User = user,
                Hwids = _context.HwidInfo.ToList()
            });
        }

        // GET: Hwid/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            User user = HttpContext.Session.GetObject<User>("user");
            if (user == null)
            {
                return RedirectToAction("Index", "Auth");
            }

            if (id == null)
            {
                return NotFound();
            }

            var hwidInfo = await _context.HwidInfo
                .FirstOrDefaultAsync(m => m.Id == id);
            if (hwidInfo == null)
            {
                return NotFound();
            }

            return View(new HwidViewModel
            {
                User = user,
                Hwid = hwidInfo
            });
        }

        // GET: Hwid/Create
        public IActionResult Create()
        {
            User user = HttpContext.Session.GetObject<User>("user");
            if (user == null)
            {
                return RedirectToAction("Index", "Auth");
            }
            return View(new HwidViewModel
            {
                User = user
            });
        }

        // POST: Hwid/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(HwidViewModel hwidViewModel)
        {
            User user = HttpContext.Session.GetObject<User>("user");
            if (user == null)
            {
                return RedirectToAction("Index", "Auth");
            }
            if (ModelState.IsValid)
            {
                _context.Add(hwidViewModel.Hwid);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(new HwidViewModel
            {
                User = user,
                Hwid = hwidViewModel.Hwid
            });
        }

        // GET: Hwid/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            User user = HttpContext.Session.GetObject<User>("user");
            if (user == null)
            {
                return RedirectToAction("Index", "Auth");
            }
            if (id == null)
            {
                return NotFound();
            }

            var hwidInfo = await _context.HwidInfo.FindAsync(id);
            if (hwidInfo == null)
            {
                return NotFound();
            }
            return View(new HwidViewModel
            {
                User = user,
                Hwid = hwidInfo
            });
        }

        // POST: Hwid/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, HwidViewModel hwidViewModel)
        {
            User user = HttpContext.Session.GetObject<User>("user");
            if (user == null)
            {
                return RedirectToAction("Index", "Auth");
            }
            if (id != hwidViewModel.Hwid.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(hwidViewModel.Hwid);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HwidInfoExists(hwidViewModel.Hwid.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(new HwidViewModel
            {
                User = user,
                Hwid = hwidViewModel.Hwid
            });
        }

        // GET: Hwid/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            User user = HttpContext.Session.GetObject<User>("user");
            if (user == null)
            {
                return RedirectToAction("Index", "Auth");
            }
            if (id == null)
            {
                return NotFound();
            }

            var hwidInfo = await _context.HwidInfo
                .FirstOrDefaultAsync(m => m.Id == id);
            if (hwidInfo == null)
            {
                return NotFound();
            }

            return View(new HwidViewModel
            {
                User = user,
                Hwid = hwidInfo
            });
        }

        // POST: Hwid/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            User user = HttpContext.Session.GetObject<User>("user");
            if (user == null)
            {
                return RedirectToAction("Index", "Auth");
            }
            var hwidInfo = await _context.HwidInfo.FindAsync(id);
            _context.HwidInfo.Remove(hwidInfo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Verify(string hwid)
        {
            var hwidInfo = await _context.HwidInfo.FirstOrDefaultAsync(hwidInfo => hwidInfo.Value.ToLower() == hwid.ToLower());
            if (hwidInfo == null)
            {
                return Unauthorized();
            }
            return Ok();
        }

        private bool HwidInfoExists(int id)
        {
            return _context.HwidInfo.Any(e => e.Id == id);
        }
    }
}

HwidProtectionServer/Views/Shared/_Layout.cshtml
@model HwidProtectionServer.ViewModels.BaseViewModel

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HwidProtectionServer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HwidProtectionServer</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hwid" asp-action="Index">Hwid</a>
                        </li>
                        @if (Model.User == null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Logout">Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - HwidProtectionServer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>